medicalapp/urls.py
from django.urls import path
from django.urls.conf import include

from . import views
from .views import (DiseaseListView, DoctorDetailView, DoctorListView,
                    FieldListView, HospitalListView, SearchListView)

urlpatterns = [
    path('', views.home_page, name='home'),
    path('doctors/', DoctorListView.as_view(), name='doctor-list'),
    path('doctor/<int:pk>/', DoctorDetailView.as_view(), name='doctor-detail'),
    path('hospitals/', HospitalListView.as_view(), name='hospital-list'),
    path('speciality/', FieldListView.as_view(), name='field-list'),
    path('disease/', DiseaseListView.as_view(), name='disease-list'),
    path('search/', SearchListView.as_view(), name='search-list'),
    path('register/',views.register,name = "register"),
    path('login/',views.login,name = "login"),
    
    # path('accounts/',include("accounts.urls"))
]

medicalproject/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('medicalapp.urls'))
 
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

medicalapp/models.py
from django.db import models
from django.urls import reverse
from django_resized import ResizedImageField
from PIL import Image


class Disease(models.Model):
    name = models.CharField(max_length=70)
    parent = models.ForeignKey(
        'self', blank=True, null=True, related_name='disease', on_delete=models.CASCADE)

    # def __self__(self):
    #     return self.name

    def __str__(self):
        return f'{self.name}'


class Field(models.Model):
    name = models.CharField(max_length=70)

    # def __self__(self):
    #     return self.name

    def __str__(self):
        return f'{self.name}'


class Doctor(models.Model):
    name = models.CharField(max_length=50)
    bio = models.TextField()
    image = ResizedImageField(default='default.svg', size=[
                              300, 300], upload_to='doctor_images')
    fields = models.ForeignKey(Field, on_delete=models.CASCADE)
    treats = models.ManyToManyField(Disease)

    # def __self__(self):
    #     return self.name

    def __str__(self):
        return f'{self.name}'

    # def get_absolute_url(self):
    #     return reverse('', kwargs={'pk': self.pk})


class Hospital(models.Model):
    name = models.CharField(max_length=100)
    area = models.CharField(max_length=70)
    division = models.CharField(max_length=30)
    city = models.CharField(max_length=50)
    link = models.URLField(null=True, blank=True)
    image = ResizedImageField(default='hospital.svg', size=[
                              300, 300], upload_to='hospital_images')
    doctors = models.ManyToManyField(Doctor)

    # def __self__(self):
    #     return self.name

    def __str__(self):
        return f'{self.name}'

    # def get_absolute_url(self):
    #     return reverse('', kwargs={'pk': self.pk})

medicalapp/forms.py
from django import forms
from django.db.models import fields
from .models import Doctor

# Create your forms here.

class NewUserForm(forms.ModelForm):
    class Meta:
        model = Doctor
        fields = []

medicalapp/views.py
from django.db.models import Q
from django.shortcuts import HttpResponse, render
from django.views.generic import DetailView, ListView

from .models import Disease, Doctor, Field, Hospital


def home_page(request):
    return render(request, 'medicalapp/home.html')

def register(request):
    
    return render(request, 'medicalapp/register.html')
def login(request):
    return render(request, 'medicalapp/login.html')

class DoctorListView(ListView):
    model = Doctor
    template_name = 'medicalapp/doctors_list.html'
    context_object_name = 'doctors'
    ordering = ['name']
    paginate_by = 10


class DoctorDetailView(DetailView):
    model = Doctor


class HospitalListView(ListView):
    model = Hospital
    template_name = 'medicalapp/hospital_list.html'
    context_object_name = 'hospitals'
    ordering = ['name']
    paginate_by = 10


class FieldListView(ListView):
    model = Field
    template_name = 'medicalapp/field_list.html'
    context_object_name = 'fields'
    ordering = ['name']
    paginate_by = 10


class DiseaseListView(ListView):
    model = Disease
    template_name = 'medicalapp/disease_list.html'
    context_object_name = 'diseases'
    ordering = ['name']
    paginate_by = 10


class SearchListView(ListView):
    model = Doctor
    template_name = 'medicalapp/search_list.html'
    ordering = ['name']
    paginate_by = 15

    def get_queryset(self):
        query = self.request.GET.get('q')
        # doctor_list = Doctor.objects.filter(
        #     Q(name__icontains="x") | Q(bio__icontains="x") | Q(fields__name__icontains="neuro") | Q(hospital__name__icontains="sq"))
        doctor_list = Doctor.objects.filter(Q(name__icontains=query) | Q(bio__icontains=query) | Q(
            fields__name__icontains=query) | Q(hospital__name__icontains=query) | Q(hospital__name__icontains=query) | Q(
            hospital__area__icontains=query) | Q(hospital__division__icontains=query) | Q(hospital__city__icontains=query) | Q(
            treats__name__icontains=query)).distinct()

        return doctor_list

medicalapp/templates/medicalapp/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="{% static 'medicalapp/main.css' %}">
  <title>DocTracker</title>  
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-BmbxuPwQa2lc/FVzBcNJ7UAyJxM6wuqIj61tLrc4wSX0szH/Ev+nYRRuWlolflfl" crossorigin="anonymous">
  <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.6.0/dist/umd/popper.min.js"
    integrity="sha384-KsvD1yqQ1/1+IA7gi3P0tyJcT3vR+NdBTt13hSJ2lnve8agRGXTTyNaBYmCR/Nwi" crossorigin="anonymous">
  </script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/js/bootstrap.min.js"
    integrity="sha384-nsg8ua9HAw1y0W1btsyWgBklPnCUAFLuTMS2G72MMONqmOymq585AcH49TLBQObG" crossorigin="anonymous">
  </script>
  <link rel="stylesheet" href="https://pro.fontawesome.com/releases/v5.10.0/css/all.css"
    integrity="sha384-AYmEC3Yw5cVb3ZcuHtOA93w35dYTsvhLPVnYs9eStHfGJvOvKxVfELGroGkvsg+p" crossorigin="anonymous" />


</head>

<body style="font-family: 'Product Sans', serif;">


   
    {% block content %}
    {%endblock content %}
    
  <section id="footer">
    <div class="footerContainer">
      <div class="first">
        <h2>FAQs</h2>
        <p>I don't know how to search ? <br>
          aAfter clicking it's not showing any results ? <br> I'm a doctor, I'd would like to update my info <br>
          Can I search other things here ?</p>
      </div>
      <div class="second">
        <p>I'd like to find all neuro//anysurgeon,how can I do that ? <br>
          Can I find therapists here ? <br>Can I find nurses here ? <br> aCan I get doctors' contact no here ? <br> Do you guys have affiliation with any doctor ?</p>
      </div>
      <div class="third">
        <p>Are there any paid subscriptions ? <br>
          Can I directly talk to a doctor from here ? <br>Is this website secured ? <br> Is it necessary to login/create account ? <br>I think I have seen some doctors with wrong info,
          how can I report for corrections ?</p>
      </div>
      <div class="fourth">
        <li><a style="color: white;" href="{% url 'home' %}">Home</a></li>
        <li><a style="color: white;" href="{% url 'doctor-list' %}">Doctors' List</a></li>
        <li><a style="color: white;" href="{% url 'register' %}">Register</a></li>
        <li><a style="color: white;" href="{% url 'login' %}">Login</a></li>
        <li><a style="color: white;" href="#">Contact Us</a></li>
        <li><a style="color: white;" href="http://127.0.0.1:8000/admin/medicalapp/doctor/">About Us</a></li>
      </div>
    </div>
    <div class="footerEnd">
      <small><p>&copy; Copyright 2020, All right reserved by  <a href="https://github.com/Btocode">AFSAN</a> </p>
        </small>
    </div>
  </section>


</body>

</html>

medicalapp/templates/medicalapp/disease_list.html
{% extends 'medicalapp/listbase.html' %}
{% block content %}

<div class="container">
    <div class="listContainer" style="height: 100%; padding: 20pt; width: 80%;">
      <div class="list-table">
        <h2 style="text-align: center; margin-top: 10pt">Showing Doctor List By Disease</h2>    
       
    {% for disease in diseases %}
    {% if disease.doctor_set.all %}
    <h3> {{disease.name}} </h3>
    <table class="table table-hover" style="border: 2pt solid #ccc; overflow:hidden ; box-sizing: border-box; box-shadow: 1pt 1pt .5pt 1pt #ccc;">
        <thead>
    
  </thead>
  <tbody>
    {% for doctor in disease.doctor_set.all %}
    <tr class="tablerow" style="text-align: left;">
      <th scope="row" style="width: 60pt;"><img class="meta-image" src="{{ doctor.image.url }}" alt="{{ doctor.name }}}"> </th>
      <td style="width: 250pt;">
        <a href="{% url 'doctor-detail' doctor.id %}" 
        style="text-decoration: none; color: black; text-transform: uppercase;">{{doctor.name}}</a></td>
      <td style="width: 200pt;" >
        <p style="text-align: left;" >
        {% if doctor.hospital_set.all %}  
        {% for hospital in doctor.hospital_set.all %}        
        {{hospital.name}}
            
        {% endfor %}
        {% else %}
      No Hospital
            {% endif %}
          </p>
      </td>      
      <td style="width: 200pt;">
        <p >
        {% for disease in doctor.treats.all %}
          {{disease}},
        {% endfor %}
        </p>
      </td>
      <td style="width: 200pt;">
        {% if doctor.hospital_set.all %}  
          {% for hospital in doctor.hospital_set.all %}
            {% if hospital.link %}
          <p style="display: flex; justify-content: center;">
            <a class="btn btn-success" href="{{ hospital.link }}" > Available </a> </p>
          {% else %}
          <p style="display: flex; justify-content: center;">Not Available</p>
          {% endif %}
          {% endfor %}
          {% else %}
          <p style="display: flex; justify-content: center;">Not Available</p>
          {% endif %}
        
      </td> 
      
    </tr> 
    {% endfor %} 
    {% else %}
    {% endif %}
</tbody>
</table>
    
    {% endfor %} 
{% endblock content %}

medicalapp/templates/medicalapp/doctor_detail.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Profile</title>
    <link rel="stylesheet" href="{% static 'medicalapp/profile.css' %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-BmbxuPwQa2lc/FVzBcNJ7UAyJxM6wuqIj61tLrc4wSX0szH/Ev+nYRRuWlolflfl" crossorigin="anonymous">
  <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.6.0/dist/umd/popper.min.js"
    integrity="sha384-KsvD1yqQ1/1+IA7gi3P0tyJcT3vR+NdBTt13hSJ2lnve8agRGXTTyNaBYmCR/Nwi" crossorigin="anonymous">
  </script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/js/bootstrap.min.js"
    integrity="sha384-nsg8ua9HAw1y0W1btsyWgBklPnCUAFLuTMS2G72MMONqmOymq585AcH49TLBQObG" crossorigin="anonymous">
  </script>
  <link rel="stylesheet" href="https://pro.fontawesome.com/releases/v5.10.0/css/all.css"
    integrity="sha384-AYmEC3Yw5cVb3ZcuHtOA93w35dYTsvhLPVnYs9eStHfGJvOvKxVfELGroGkvsg+p" crossorigin="anonymous" />

</head>
<body style="font-family: 'Product Sans', sans-serif;">
    <div class="container">
        <section id="profile-header">
            <header>
                <div class="container">
                    <div class="head">
                        <div class="img-container">
                            <img src="{{ object.image.url }}" alt="" style="box-shadow: 1pt 1pt 1pt 1pt #ccc; border: 2pt solid #ccc;">
                        </div>
                        <div class="desc-container">
                            <h2  style="font-family: 'Product Sans', sans-serif;" >{{object.name}}</h2>
                            <p style="font-family: 'Product Sans', sans-serif;">{{object.fields}}; 
                                {% for disease in object.treats.all %}
                                {{disease}},
                                {% endfor %}
                            </p>
                            <h5 style="font-family: 'Product Sans', sans-serif;">
                                {% for hospital in object.hospital_set.all %}
                                {{hospital.name}}
                                {% endfor %}
                            </h5>
                            {% for hospital in object.hospital_set.all %}                            
                            {% if hospital.link %}
                                <a class="btn btn-success" style="margin-top: 10pt;" href="{{ hospital.link }}" >Make Appointment</a>
                            {% else %}
                            {% endif %}
                            {% endfor %}
                        </div>
                    </div>
                    <div class="bottom">
                        <h3 style="font-family: 'Product Sans', sans-serif;">About</h3>
                        <p style="font-family: 'Product Sans', sans-serif;">
                            {{object.bio}}
                        </p>
                    </div>
                </div>
            </header>
        </section>
    </div>
</body>
</html>

medicalapp/templates/medicalapp/doctors_list.html
{% extends 'medicalapp/listbase.html' %}
{% block content %}
<div class="container">
  <div class="listContainer" style="height: 100%; padding: 20pt; border: 2px solid #ccc; border-radius: 10px; width: 80%;">
    <div class="list-table">
      <h2 style="text-align: center;  margin-top: 10pt;">Showing All Doctors List</h2>
      <table class="table table-hover">
        <thead>
    <tr>
      <th scope="col"></th>
      <th scope="col"><label for="">Name</label></th>
      <th scope="col"><label for="">Hospital/Chamber</label></th>
      <th scope="col"><label for="">Speciality</label></th>
      <th scope="col"><label for="">Disease Treatements</label></th>
      <th scope="col"><label for="">Remote Appointment</label></th>
    </tr>
  </thead>
  <tbody>
    {% for doctor in doctors %}
    <tr class="tablerow">
      <th scope="row"><img class="meta-image" src="{{ doctor.image.url }}" alt="{{ doctor.name }}}"> </th>
      <td>
        <a href="{% url 'doctor-detail' doctor.id %}" 
        style="text-decoration: none; color: black; text-transform: uppercase;">{{doctor.name}}</a></td>
      <td>
        {% for hospital in doctor.hospital_set.all %}
            {{hospital.name}}
        {% endfor %}
      </td>
      <td>{{ doctor.fields}}</td>
      <td>
        {% for disease in doctor.treats.all %}
          {{disease}},
        {% endfor %}
      </td>
      <td>
        {% for hospital in doctor.hospital_set.all %}
          {% if hospital.link %}
            <a class="btn btn-success" href="{{ hospital.link }}" > Available </a>
          {% else %}
            Not Available
          {% endif %}
        {% endfor %}
      </td> 
      
    </tr> 
    {% endfor %} 
  </tbody>
</table>

{% endblock content %}
    

medicalapp/templates/medicalapp/field_list.html
{% extends 'medicalapp/listbase.html' %}
{% block content %}

<div class="container">
  <div class="listContainer" style="height: 100%; padding: 20pt; width: 80%;">
    <div class="list-table">
    
        <h2 style="text-align: center;  margin-top: 10pt;">Showing Doctor List By Speciality</h2>
    {% for field in fields %}
    {% if field.doctor_set.all %}
    <h3> {{field.name}} </h3>
    <table class="table table-hover" 
    style="border: 2pt solid #ccc; overflow:hidden ; box-sizing: border-box; box-shadow: 1pt 1pt .5pt 1pt #ccc; margin-bottom: 50pt;">
        <thead>
    
  </thead>
  <tbody>
    {% for doctor in field.doctor_set.all %}
    <tr class="tablerow" style="text-align: left;">
      <th scope="row" style="width: 60pt;"><img class="meta-image" src="{{ doctor.image.url }}" alt="{{ doctor.name }}}"> </th>
      <td style="width: 250pt;">
        <a href="{% url 'doctor-detail' doctor.id %}" 
        style="text-decoration: none; color: black; text-transform: uppercase;">{{doctor.name}}</a></td>
      <td style="width: 200pt;" >
        <p style="text-align: left;" >
        {% if doctor.hospital_set.all %}  
        {% for hospital in doctor.hospital_set.all %}        
        {{hospital.name}}
            
        {% endfor %}
        {% else %}
      No Hospital
            {% endif %}
          </p>
      </td>      
      <td style="width: 200pt;">
        <p >
        {% for disease in doctor.treats.all %}
          {{disease}},
        {% endfor %}
        </p>
      </td>
      <td style="width: 200pt;">
        {% if doctor.hospital_set.all %}  
          {% for hospital in doctor.hospital_set.all %}
            {% if hospital.link %}
          <p style="display: flex; justify-content: center;">
            <a class="btn btn-success" href="{{ hospital.link }}" > Available </a> </p>
          {% else %}
          <p style="display: flex; justify-content: center;">Not Available</p>
          {% endif %}
          {% endfor %}
          {% else %}
          <p style="display: flex; justify-content: center;">Not Available</p>
          {% endif %}
        
      </td> 
      
    </tr> 
    {% endfor %} 
    {% else %}
    {% endif %}
</tbody>
</table>
    
    {% endfor %} 
{% endblock content %}

medicalapp/templates/medicalapp/home.html
{% extends 'medicalapp/base.html' %}
{% block content %}
<section id="home-section">
<div class="navContainer">

</div>
</nav>
</div>


<div class="bglogo" style="height: 200pt; width: 200pt; margin-left: 33%; margin-bottom: 90%; margin-top: 0%;">
  <!-- <img src="/logo.png" style="width: 200pt; height: 200pt; border-radius: 50%; display: block; margin:auto;"> -->
  
</div>
<div class="bgcontainer">
  <img src="/background.svg" alt="homepage">
  <div class="searchbar" >
    <form action="{% url 'search-list' %}" method="get">
    <input name="q" type="text" placeholder="Type and hit Enter">
  </form>
    
  </div>

</div>
<div class="optcontainer">
  <div class="selectors">
    <a class="icon-button" href="{% url 'doctor-list' %}"><img src="/doctor_face.svg" alt=""></a>
    <p>See Doctor's List</p>
  </div>
  <div class="selectors">
    <a class="icon-button" href="{% url 'hospital-list' %}"><img src="/hospital.svg" alt=""></a>
    <p>Look for a hospital</p>
  </div>
  <div class="selectors">
    <a class="icon-button" href="{% url 'field-list' %}"><img src="/speciality.svg" alt=""></a>
    <p>Find Doctor's by speciality</p>
  </div>
  <div class="selectors">
    <a class="icon-button" href="{% url 'disease-list' %}"><img src="/disease.svg" alt=""></a>
    <p>find Doctor's by diseases</p>
  </div>
</div>
</section>

<section id="about-section">
<div class="ab-container">
  <div class="leftPart">
    <h3>FIND DOCTORS AROUND INSTANTLY </h3>
    <p>DOCTORS ARE ALWAYS WAITING TO HELP YOU. AND THROUGH OUR DOCFIND YOU CAN FIND 
YOUR DESIRED AND NEAREST DOCTORS EASILY. OUR DATABASE CONTAINS THOUSANDS OF DOCTORS 
ALL AROUND BANGLADESH. </p>
<p>
IF YOU ARE IN DIRE NEED OF ONE AND DON'T KNOW WHERE TO LOOK? FEAR NOT! WITH OUR ADVANCED
SEARCH ENGINE AND HUGE COLLECTION OF DOCTORS, YOU CAN EASILY LOOK FOR ONE RIGHT AWAY!
</p>
<p>
ALL THESE SERVICES ARE TOTALLY FREE OF SERVICES. ISN'T IT COOL? AND WE ARE WORKING CONTINUOSLY
TO ADD AND UPDATE OUR DATABASE EVERY DAY. WITH EVERY SEARCH YOU MAKE, IT KEEPS GETTING BETTER.
</p>



    
  </div>
  <div class="rightPart">
    <h2>Learn How to Search<br> the Best Way</h2>
    <div class="videoContainer">
      <video src="/video.mp4" preload="auto"></video>
    </div>
  </div>
</div>
</div>
</section>
{% endblock content %}

medicalapp/templates/medicalapp/hospital_list.html
{% extends 'medicalapp/listbase.html' %}
{% block content %}

<div class="container">
  <div class="listContainer" style="height: 100%; padding: 20pt; border: 2px solid #ccc; border-radius: 10px; width: 80%;">
      <div class="list-table">
        <h2 style="text-align: center; margin-top: 10pt;">Showing Hospital List</h2>
        <table class="table table-hover">
<thead>
    <tr>
      <th scope="col"></th>
      <th scope="col"><label for="">Hospital Name</label></th>
      <th scope="col"><label for="">Area</label></th>
      <th scope="col"><label for="">Location</label></th>
      <th scope="col"><label for="">Doctors</label></th>
      <th scope="col"><label for="">Remote Appointment</label></th>
    </tr>
  </thead>
  <tbody>
    {% for hospital in hospitals %}
    <tr class="tablerow">
      <th scope="row"><img class="meta-image" src="{{ hospital.image.url }}" alt="{{ hospital.name }}}"> </th>
      <td>
        {{hospital.name}}</td>
      <td>
        {{ hospital.area}}
      </td>
      <td>
          {{ hospital.city }}, {{ hospital.division }}
      </td>
      <td>
        <a class="btn btn-primary" href="{% url 'doctor-list' %}" > See Doctors List </a>
      </td>
      <td>        
          {% if hospital.link %}
            <a class="btn btn-success" href="{{ hospital.link }}" > Available </a>
          {% else %}
            Not Available
          {% endif %}        
      </td> 
      
    </tr> 
    {% endfor %} 

{% endblock content %}

medicalapp/templates/medicalapp/listbase.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Search Doctors</title>
  <link rel="stylesheet" href="{% static 'medicalapp/listpage.css' %}">
  <link rel="stylesheet" href="{% static 'medicalapp/main.css' %}">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-BmbxuPwQa2lc/FVzBcNJ7UAyJxM6wuqIj61tLrc4wSX0szH/Ev+nYRRuWlolflfl" crossorigin="anonymous">
  <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.6.0/dist/umd/popper.min.js"
    integrity="sha384-KsvD1yqQ1/1+IA7gi3P0tyJcT3vR+NdBTt13hSJ2lnve8agRGXTTyNaBYmCR/Nwi" crossorigin="anonymous">
  </script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/js/bootstrap.min.js"
    integrity="sha384-nsg8ua9HAw1y0W1btsyWgBklPnCUAFLuTMS2G72MMONqmOymq585AcH49TLBQObG" crossorigin="anonymous">
  </script>
  <link rel="stylesheet" href="https://pro.fontawesome.com/releases/v5.10.0/css/all.css"
    integrity="sha384-AYmEC3Yw5cVb3ZcuHtOA93w35dYTsvhLPVnYs9eStHfGJvOvKxVfELGroGkvsg+p" crossorigin="anonymous" />
</head>

<body style="font-family: 'Product Sans', serif;">
  
 
          {% block content %}
          {% endblock content %}
          
        
  <div style="text-align: center;">
    {% if is_paginated %}
        {% if page_obj.has_previous %}
            <a class="btn btn-outline-primary mb-4" href="?page=1">Latest</a>
            <a class="btn btn-outline-secondary mb-4" href="?page={{page_obj.previous_page_number}}">
                <i class="fa fa-angle-left" aria-hidden="true"></i> <span class="pl-.5">Previous</span>
            </a>
        {% endif %}

        {% for num in page_obj.paginator.page_range %}
            {% if page_obj.number == num %}
                <a class="btn btn-secondary mb-4" href="?page={{num}}"> {{num}}</a>
            {% elif num > page_obj.number|add:'-4' and num < page_obj.number|add:'4' %}
                <a class="btn btn-outline-secondary mb-4" href="?page={{num}}"> {{num}}</a>
            {% endif %}
        {% endfor %}

        {% if page_obj.has_next %}
            <a class="btn btn-outline-secondary mb-4" href="?page={{page_obj.next_page_number}}">
                <span class="pr-.5">Next</span> <i class="fa fa-angle-right" aria-hidden="true"></i>    
            </a>
            <a class="btn btn-outline-primary mb-4" href="?page={{page_obj.paginator.num_pages}}">Oldest</a>
        {% endif %}

    {% endif %}
    </div>
    <br>
    <!--I know it isn't supposed to written this but I wrote it anyways-->
    {% if page_obj.paginator.count > page_obj.number|add:'6' %}
        <h4 class="mb-3" style="text-align: center;">
            Total Results: {{ page_obj.paginator.count }}
        </h4>
    {% endif %} 

</div>
</div>
</div>

</body>

</html>

medicalapp/templates/medicalapp/search_list.html
{% extends 'medicalapp/listbase.html' %}
{% block content %}
<div class="searchbar" style="height: 50px; width: 100%; display: flex; justify-content: center; margin-top: 10px;"> 
  <form action="{% url 'search-list' %}" method="get">
  <input name="q" type="text" placeholder="Search Here" 
  style="height: 40px; width: 400px; border: 2px solid #ccc; border-radius: 15px; padding: 10px 20px; ">
</form>
  <button class="btn btn-outline-primary" style="margin-left: 20px ; height: 40px; border-radius: 15px;" action="{% url 'search-list' %}" type="submit">Search</button>
</div>

<div class="container">
  <div class="listContainer">
    <div class="list-table">
      <table class="table table-hover">
<thead>
  <tr>
    <th scope="col"></th>
    <th scope="col"><label for="">Name</label></th>
    <th scope="col"><label for="">Hospital/Chamber</label></th>
    <th scope="col"><label for="">Speciality</label></th>
    <th scope="col"><label for="">Disease Treatements</label></th>
    <th scope="col"><label for="">Remote Appointment</label></th>
  </tr>
</thead>
<tbody>
  {% for doctor in object_list %}
  <tr class="tablerow">
    <th scope="row"><img class="meta-image" src="{{ doctor.image.url }}" alt="{{ doctor.name }}}"> </th>
    <td>
        <a href="{% url 'doctor-detail' doctor.id %}" 
        style="text-decoration: none; color: black; text-transform: uppercase;">{{doctor.name}}</a></td>
    <td>
      {% for hospital in doctor.hospital_set.all %}
          {{hospital.name}}
      {% endfor %}
    </td>
    <td>{{ doctor.fields}}</td>
    <td>
      {% for disease in doctor.treats.all %}
        {{disease}},
      {% endfor %}
    </td>
          
    <td>
    {% for hospital in doctor.hospital_set.all %}                            
    {% if hospital.link %}
    
    <a class="btn btn-success" href="{{ hospital.link }}" >Available</a>
    {% else %}
    {% endif %}
    {% endfor %}
    </td> 
      
    
  </tr> 
  {% endfor %} 
</tbody>
</table>

{% endblock content %}